BranchMetrics/documentation

- ingredients/events/custom_events.md
The example code for attaching custom metadata on Android was missing code formatting.
> Adds missing Android custom metadata code formatting

- ingredients/webhooks/add.md
@pccyang added clicks as events for webhooks in a few parts of the webhook docs.  Let me know if there are other areas of the webhook docs that also need updates b/c of the new click event.  Thanks!
> added link click as standard event for webhook docs

- recipes/analytics_mixpanel.md
Apparently the recipe had referenced wrong parameter name, so I found appropriate constant in SDK source
> Actualize Mixpanel recipe

- recipes/app_download_banner.md
added a code snippet to prepend a default country code to the smart banner phone number.
> prepend country code to smart banner

- pages/getting-started/sdk-integration-guide.md
- pages/getting-started/universal-app-links.md
@aaustin 
Tweaks:
1. Converted the installation command parameters into a table ([here](https://github.com/BranchMetrics/documentation/compare/cordova-2-0-tweaks?expand=1#diff-aeba1c29195c68d364092cfa8e1c71bfR92))
1. Updated the installation command's value stubs to match those used on other platforms ([here](https://github.com/BranchMetrics/documentation/compare/cordova-2-0-tweaks?expand=1#diff-aeba1c29195c68d364092cfa8e1c71bfR100), [here](https://github.com/BranchMetrics/documentation/compare/cordova-2-0-tweaks?expand=1#diff-aeba1c29195c68d364092cfa8e1c71bfR107), and [here](https://github.com/BranchMetrics/documentation/compare/cordova-2-0-tweaks?expand=1#diff-aeba1c29195c68d364092cfa8e1c71bfR104))
1. Removed the Universal Links section from the SDK integration guide, since it …
> Some reformatting and step simplification

- pages/getting-started/branch-universal-object.md
@aaustin 
I extrapolated the new callback examples for Cordova and added them to Titanium too. I can't see any reason it would be wrong, but a quick sanity check would be awesome.
The `redeemRewards()` method documentation didn't need any updates...weird
> Update BUO shareSheet methods

- pages/features/content-sharing.md
- pages/features/custom-onboarding.md
- pages/features/email-campaigns.md
- pages/features/facebook-app-invites.md
- pages/features/index.md
- pages/features/referral-programs.md
- pages/features/twitter-ads.md
- pages/third-party-integrations/google-analytics.md
- pages/third-party-integrations/mixpanel.md
- pages/third-party-integrations/referral-saasquatch.md
@lilabjorg looks like platform-specific page titles weren't getting processed. Those were only left from the old portal on a few pages, so I removed them. Does this look good?
> Some page titles were not showing up

- pages/features/smart-banner.md
The previous example was only for .com urls, and didn't actually work with those (window.location is not a string)
@aaustin
> Fix the example to be functional

- pages/features/referral-programs.md
- pages/getting-started/sdk-integration-guide.md
@aaustin could you do a quick 👍 on this, since I believe you're the only one fluent in Xamarin?
(setDebug flags are on a separate page in the docs, so I removed them from the SDK integration instructions to keep all platforms the same)
> Make docs match GitHub README

- pages/getting-started/universal-app-links.md
The Fabric team found this, and I've just confirmed. Xcode will automatically update developer.apple.com once you enable the Associated Domains entitlement in your project. We don't need to send people there anymore.
> Remove developer.apple.com step in Universal Links

- pages/getting-started/configuring-links.md
@derrickstaten added a section in getting started > configuring links, under Link Control Parameters, Redirect Customization (http://127.0.0.1:4000/getting-started/configuring-links/#web-only-links)
I think we can keep it real brief.
> [HOLD for testing & deploy] started section for web-only links

- pages/getting-started/creating-links-in-apps.md
Small addition (just a protip) on the "Creating Links in Apps" page explaining what happens when getShortUrl fails, and why that can result in a really long link.
> Protip explaining offline link generation behavior

- pages/getting-started/configuring-links.md
We don't have any ios_weibo flag in our LS code. However, we have an android_wechat_url flag that we don't advertise on the docs so I am swapping these values.
@dwestgate cc @aaustin
> remove weibo flag and add android_wechat

- pages/getting-started/deep-link-routing.md
- pages/getting-started/sdk-integration-guide.md
This updates the code snippets to use the registerDeepLinkHandler version of initSession instead of automaticallyDisplayDeepLinkHandler
cc @dwestgate and @ahmednawar
> DOCS-66 Updated initSession code snippets

- pages/third-party-integrations/apptimize.md
- pages/third-party-integrations/referral-saasquatch.md
Small commit to put the docs back in line with Branch deep link naming convention. 
CC @dwestgate & @ahmednawar
> Replace deeplink with deep link

- pages/features/journeys.md
Fixed a broken link on the Journeys page. @aeromusek Can you do a quick review?
> Remove "qa" from Source Analytics link

- pages/getting-started/branch-universal-object.md
Are whitespace cleanups ok? seemed better to have consistent no trailing spaces, but if needed I can redo PR with just the contentTitle -> title change.
> react-native contentTitle -> title

- pages/third-party-integrations/responsys.md
- pages/third-party-integrations/sailthru.md
- pages/third-party-integrations/salesforce.md
- pages/third-party-integrations/sendgrid.md
@derrickstaten you can no longer add the entitlements file to the target in newer versions of Xcode. It is not required to add it to the target. This PR removes the references to this step in the setup pages for email.
> update email-ul instructions

- pages/getting-started/sdk-integration-guide.md
- Mention key differences between 0.9 and 1.0.
- Refer readers to the GitHub repo for details.
- Recommend `pod install --repo-update` in case users have an outdated pod repo.
> React Native updates explaining 0.9 vs 1.0

- pages/getting-started/universal-app-links.md
Android teams that are silo'd from iOS easily miss the -alternate piece.
> Added alternate domain for setting up Android Applinks.

- pages/getting-started/link-behavior.md
@EvangelosG This [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=638672) seems to be fixed.
Do you think we should completely remove info about it or state that there used to be a bug?
> Removing info about Chrome bug, since it was fixed.

- pages/getting-started/content-sharing-tutorial.md
- pages/getting-started/sdk-integration-guide.md
- pages/getting-started/universal-app-links.md
Updated integration guide to use the new preferred '[[Branch getInstance] application:application openURL:url options:options];' method instead of '[[Branch getInstance] handleDeepLink:url]'.
> Updated integration guide to use the new preferred deeplink method.

- pages/marketing-channels/deepviews.md
Although it should redirect automatically to the new endpoint, for some reason this link doesn't. I've changed it to point to the same place, but in the new /marketing-channels/ section.
> Fixed broken link in Deepviews page.

- pages/getting-started/deep-link-routing.md
- pages/getting-started/sdk-integration-guide.md
- pages/getting-started/universal-app-links.md
Also added a warning that the observer for the "kit loaded" event has to be added prior to the mParticle session initialization.
> Added swift examples for the iOS mParticle-only code.

- pages/data-exchange/appsflyer.md
Caution to ensure that fingerprinting is enabled on the Appsflyer Android app for Branch to attribute installs properly.
> Added caution for Android Appsflyer DI

- _data/sidebar.yml
- pages/data-exchange/appboy.md
- pages/marketing-channels/appboy-push-service.md
Guide to integrate Branch with Appboy is added under section marketing-channel -> Push service -> Appboy push service
http://127.0.0.1:4000/marketing-channels/appboy-push-service/overview/
While the Appboy in Data-Integration section is changed, where the support section is removed.
> Appboy push service support docs added - INTENG-3447

- pages/marketing-channels/spotlight-indexing.md
@aaaronlopez this is the fix for the broken link. We recently did a navigation change on the documentation which changes the locations of all our pages. The link on https://dev.branch.io/getting-started/branch-universal-object/guide/ios/#listonspotlightwithcallback was still pointing to the old page location. I updated the `alias` on the new page so the old link will redirect correctly.
> fix: broken link on

- pages/marketing-channels/google-ads-overview.md
- pages/marketing-channels/google-conversions.md
Note: The term `adwords` in the URL path gets blocked by adblockers
> Image URL fix.

- pages/getting-started/sdk-integration-guide.md
Key is defined on mParticle's dashboard.
> Removed Branch key requirement for iOS mParticle.

- pages/marketing-channels/journeys.md
changes to "Deep linking from the banner or interstitial" and "Visualizing Journeys performance" sections of Journeys docs
> Add docs for passing referring link data in CTA

- _config.yml
- _config_live.yml
- _config_staging.yml
- pages/marketing-channels/facebook-ads-overview.md
_config.yml files for live and staging have incorrect baseurl setups, should be nil values
This causes the jekyll-redirect-from gem to work incorrectly. -> Reverting usage of this gem.
> Facebook ads url redirection

- pages/cross-channel-analytics/growth-attribution.md
Change: 
Added a note on the identity length for users cannot be more than 127 characters.
Tests:
Tested the documentation website locally
> Length of the Identity

- pages/marketing-channels/deepviews.md
Description of the change
Incorporated a small note, to add the alternate-app.link domain to the entitlements file for Deeplinking from the Deepview CTA
Test Plan
Tested locally.
Reviewers
@ethanneff
> Added a prerequisite to add the alternate domain for Deepviews to work.
