BranchMetrics/documentation

ingredients/sdk_setup/init_session.md
Replaced markdown code blocks with highlight blocks
Replaced isDebug variable by actual Constant
=> Fix init code and replace

ingredients/http_api/creating_deeplinks.md
@derrickstaten 
This was requested as a part of BranchMetrics/Branch-iOS-SDK#140
=> Add mention of Twitter cards, per customer request.

_plugins/youtube.rb, overviews/index.md
@jakecadams I don't know about plugins, can you double-check this for prod?
=> max fixed youtube

ingredients/sdk_links/deeplink_path.md
Added some language to - 
recipes/add_custom_link_data_and_routing/android/#specify-a-custom-deeplink-path---deeplinkpath
'You can make this platform specific by replacing $deeplink_path with $android_deeplink_path or $ios_deeplink_path'.
=> added $ios_deeplink_path and $android_deeplink_path to documentation

recipes/app_download_banner.md
Added a section to /recipes/app_download_banner/
=> Banner event listener

overviews/how_branch_links_work.md, overviews/index.md, overviews/link_creation_guide.md
Fixes to Arbitrary capitalization, couple of typos. Changed "Guide to Create Deep Links" to "Deep link creation guide"
@aaustin
=> typo fixes mainly

ingredients/app_links/applinks_issues.md
@derrickstaten @aaustin I've added additional information regarding the OG tag tester.
=> additional information to debug og tag problems

ingredients/web_sdk/send_sms_example.md
Minor.
@derrickstaten - I will work on updating the `release.sh` in web sdk so that we don't have to manually update these in the future.
=> update web sdk release version number

overviews/index.md
=> fix typo on main page

ingredients/web_sdk/_initialization.md, ingredients/web_sdk/send_sms_example.md
=> new web sdk version!

ingredients/web_sdk/_initialization.md, ingredients/web_sdk/send_sms_example.md
@dmitrig01 
would you kindly also do some manual checking to see if v1.6.9 is live and sound?
Thanks!
=> update web sdk to v1.6.9

ingredients/sdk_routing/auto_routing.md
=> fix-swyft-easy-deeplinking

ingredients/sdk_setup/ios9_restoration_handler.md, recipes/spotlight_indexing.md
@aaustin -- reported by a partner
=> Restoration handler optional

ingredients/sdk_setup/identify_and_logout.md
Update the explanation of multi-device identities and merging.
=> updated working about identity merges and how they work

ingredients/sdk_links/creating_links.md, recipes/content_sharing.md
@derrickstaten I just fixed an erroneous redirect on content sharing that previously redirected to itself.
=> fixing extraneous redirect for content sharing

recipes/deep_link_mobile_site.md
@aaustin @AustinHay FYI. Could do with a little gif in the future.
=> change deeplink SDK to website to app routing

recipes/dashboard_pro_tips.md
remove funnels from recipes>dashboard_pro_tips.md
=> remove funnels from pro_tips

ingredients/dashboard_analytics/summary.md
remove funnels from _ingredients>dashboard_analytics>summary_ in docs
=> remove funnels from dash summary in docs

ingredients/web_sdk/smart_banner.md, recipes/google_app_indexing.md
And a little app indexing cleanup. Still needs new images. Those will come tomorrow. 
cc @aaustin @AustinHay @jsaleigh
=> add smart banner features

ingredients/dashboard_setup/cloudflare_tls_setup.md, ingredients/dashboard_setup/custom_link_domain.md, recipes/branch_universal_links.md
@aaustin -- make CloudFlare / SSL / TLS docs more technical and more accurate.
=> update UL and custom link docs

ingredients/webhooks/filters_advanced.md, ingredients/webhooks/templates_advanced.md
@chanian @aaustin @derrickstaten
=> click filter and template keys

ingredients/sdk_setup/init_session.md
1. Cookie-base => Cookie-based
2. no => on
=> found minor typo

ingredients/webhooks/syntax.md
Added in the data format/example for the click event postaback
=> added example format for link click event

references/data_export_api.md
Pop, lock and subsequently, drop it.
=> Update api export docs

ingredients/dashboard_setup/cloudflare_tls_setup.md
@dmitrig01 or @wlindemann can you make sure this is alright and let me know if there is anywhere else this or related info should be changed? Thanks!
=> editing root domain CNAME to point to custom.bnc.lt instead of bnc.lt

ingredients/app_links/applinks_issues.md
@derrickstaten or @wlindemann can you thumb if all is good
=> adding in curl command for autorescraping for facebook app invites

ingredients/sdk_setup/ios9_deep_link_path.md, recipes/branch_universal_links.md
@derrickstaten this PR talks about how to handle Universal Links with old URI schemes.
=> documentation for Universal Links and old URI paths

ingredients/sdk_setup/ios9_deep_link_path.md
=> update deeplink path code

ingredients/sdk_setup/push_notifications.md, recipes/add_the_sdk.md
@aeromusek sorry to be adding stuff last minute. @Sarkar does this exist on android yet? if not, we should add it
=> Push notif

pages/getting-started/branch-universal-object.md
Updated initialization method for BUO in Swift.
=> corrected BUO initialization method in Swift

pages/getting-started/creating-links-other-ways.md
Either "lest the link breaks" or "otherwise the link will break"
I think the latter is clearer :)
=> small fix. I do not think lest means what you think it means

pages/features/smart-banner.md
=> remove redundant code for closeBanner()

pages/getting-started/deep-link-routing.md
=> android push notifications

pages/features/content-sharing.md, pages/features/custom-onboarding.md, pages/features/deepviews.md, pages/features/referral-programs.md, pages/getting-started/branch-universal-object.md, pages/getting-started/creating-links-in-apps.md, pages/getting-started/deep-link-routing.md, pages/getting-started/integration-testing.md, pages/getting-started/sdk-integration-guide.md, pages/getting-started/setting-identities.md, pages/getting-started/tracking-events.md, pages/getting-started/universal-app-links.md
=> Update cordova 2 0

pages/features/smart-banner.md
@derrickstaten could you please check this out?
=> added some messaging about Smart Banner clicks

pages/features/website-to-app-routing.md, pages/getting-started/creating-links-other-ways.md
=> Domain link issues

pages/features/website-to-app-routing.md
=> Document open app

pages/getting-started/universal-app-links.md
@derrickstaten could you please review?
@lilabjorg let me know when I could merge. Thanks!
=> new Universal Link troubleshooting question

pages/getting-started/dashboard-guide.md
@derrickstaten @aeromusek ok here we go - fresh branch, fresh PR :) encourages users to stick with one custom subdomain.
=> encourage partners to stick with just 1 subdomain

pages/getting-started/integration-testing.md
@aaustin I think this captures what we discussed this morning.
=> Clarify setDebug behavior on iOS vs Android

pages/getting-started/universal-app-links.md
@aaustin added instructions for making App Links work with custom link domains
=> Custom link domains with Android App Links

pages/getting-started/integration-testing.md
@aaustin added instructions for making App Links work in the test environment
=> Test environment link prefix needs to be added for App Links to work

pages/features/referral-programs.md
@derrickstaten I think this might help
=> Rearrange the referral programs page

pages/getting-started/sdk-integration-guide.md
@lilabjorg could you please review and merge?
=> add carthage as installation option for iOS sdk

pages/features/content-sharing.md
@lilabjorg 
I came across an extraneous "to" and am taking the opportunity to learn the process for submitting edits
=> Deleted extraneous 'to'

_includes/webhook-builder-assets/dynamic_link_builder.html, js/webhook_builders/dynamic_link_builder.js, js/webhook_builders/webhook_builder_tune.js
@aeromusek for the pull
@Johnjoe220 for oversight
:100:
=> Adding &integration_id=1993 to Tune Builder

js/webhook_builders/webhook_builder_tune.js, pages/getting-started/configuring-links.md, pages/getting-started/deep-link-routing.md
@lilabjorg @derrickstaten (also FYI to @AustinHay for a small correction I had to make so that the linter would validate)
=> Clarify what is scary

pages/getting-started/universal-app-links.md
=> troubleshooting step for users with test apps using bnc.lt

pages/features/deepviews.md, pages/features/website-to-app-routing.md
@rubinsingh for the info on the deepviews to website routing reference and fallback URLs.
@wlindemann for the `deepviewCTA()` instructions (example GIF to come...)
=> Website deepviews

ingredients/disable-click-tracking.md, pages/features/email-campaigns.md, pages/getting-started/universal-app-links.md
@derrickstaten (cc @dwestgate)
=> Add MailChimp and Mandrill links

pages/getting-started/universal-app-links.md
=> remove extra title

pages/getting-started/universal-app-links.md
@lilabjorg @1kevinchung1 I reworded slightly to fit in better with the docs style. Does this still capture the right info?
=> New FAQ section for custom aliases

pages/getting-started/universal-app-links.md
@aeromusek a tiny bit of extra guidance in that table:
=> more detail in the ul support table

pages/getting-started/universal-app-links.md
* Based off of code snippets from the Xamarin website.
* https://developer.xamarin.com/recipes/cross-platform/app-links/app-links-android/
=> Updated the section on enabling App Links for Xamarin.

pages/features/facebook-ads.md
=> Do not use setDebug with Facebook ads

pages/getting-started/webhooks.md
=> List webhook IP addresses

pages/features/referral-programs.md
Example code in the doc was not working correctly.
Hopefully this commit fixes the problem 😄
=> fix sample code of referral in android

pages/features/deepviews.md, pages/getting-started/creating-links-in-apps.md, pages/getting-started/creating-links-other-ways.md, pages/getting-started/deep-link-routing.md
@dmitrig01 could you 👍 this since we already discussed?
=> Remove /a from a bunch of places

pages/getting-started/sdk-integration-guide.md
@lilabjorg @aeromusek 
could you please take a look? Thanks
=> strong matching for app.link

pages/getting-started/sdk-integration-guide.md
An Android dev friend was confused by where to put the `branch.initSession` call. Upon looking at it, I can't see any reason combining these two instructions steps wouldn't work. Could an Android person confirm? (@Sarkar I think...?)
=> Merge two code snippets

pages/getting-started/organizing-link-data.md
@wlindemann I can't imagine I managed to mess this up, but could you give a 👍 just so we respect the process?
=> Add paramater mapping table

pages/getting-started/creating-links-in-apps.md, pages/getting-started/creating-links-other-ways.md
@dmitrig01 we chatted about this last week. Could you give a quick glance for info accuracy?
=> Clean up appending link directions

pages/getting-started/sdk-integration-guide.md
@tchingos I admit I'm not totally sure what this means, but it should close out that email you forwarded the other day:
> Hi David,
> 
> I managed to solve the compilation problem.  I thought I would let you know what I did and how we solved it.  The problem in our case was an old Facebook connect plugin which we removed.  We also added to dependences compile "io.branch.sdk.android:library:1.+”.  That was it.  Hard to find but easy to fix.  I think that dependency should be highlighted in your documentation.
> 
> Thanks!
> Howard
=> Note about gradle dependency

pages/getting-started/universal-app-links.md
@derrickstaten could I get a thumb on this?
The partner suggested putting this here: https://dev.branch.io/getting-started/sdk-integration-guide/guide/ios/#start-a-branch-session
I felt it fits better here and will still have the same visibility. Thoughts?
PS, sorry about the messy diff...automatic whitespace deletion 😞
=> New UL/FB caution message

pages/third-party-integrations/localytics.md
Very very complex and robust refactoring of the entire Jekyll structure. Fixed some Ruby native code while I was at it. 
cc @aeromusek
=> update localytics faq

pages/features/google-app-indexing.md, pages/getting-started/branch-universal-object.md
@aeromusek when you’re ready for your post, here are some updated docs
=> Update App Indexing docs

pages/features/content-sharing.md, pages/features/custom-onboarding.md, pages/features/deepviews.md, pages/features/referral-programs.md, pages/getting-started/branch-universal-object.md, pages/getting-started/creating-links-in-apps.md, pages/getting-started/deep-link-routing.md, pages/getting-started/integration-testing.md, pages/getting-started/sdk-integration-guide.md, pages/getting-started/user-value-attribution.md
@aeromusek Just doing a PR to make sure it all compiles
=> Update React Native docs

pages/getting-started/creating-links.md
@dwestgate merge this (or edit!) as you see fit. It'll live at http://dev.branch.io/getting-started/creating-links/, and won't show up in the nav
=> New landing page for link creation

pages/getting-started/integration-testing.md
@dwestgate another review for you (sorry...more automatic whitespace cleanup in this one too)
Also, this makes me want to take a shower and we should fix it:
=> Fix incorrect iOS message

pages/getting-started/sdk-integration-guide.md
@sojanpr for technical review, and @aaustin for oversight (because this explicitly reverts some of the changes in a4a649405c84e733d6f8548e9eed546d444ba255 and I'm not sure if there was a reason for those that I'm missing)
=> Clarify Android session management steps

_data/sidebar.yml, pages/third-party-integrations/amplitude.md
@aeromusek a line of code around branch-web-assets snuck in there. Not sure if it's correct or not...
=> amplitude docs

pages/third-party-integrations/appboy.md, pages/third-party-integrations/localytics.md
@aeromusek - had a support ticket come in today looking for these buttons. removed references to them.
=> move localytics and appboy to private beta

pages/features/content-sharing.md, pages/features/custom-onboarding.md, pages/features/facebook-app-invites.md, pages/features/referral-programs.md, pages/features/spotlight-indexing.md, pages/getting-started/creating-links-in-apps.md, pages/getting-started/deep-link-routing.md, pages/getting-started/sdk-integration-guide.md, pages/getting-started/universal-app-links.md, pages/third-party-integrations/apptimize.md, pages/third-party-integrations/referral-saasquatch.md
And also added check for nil in obj-c, just in case.
=> Fix for swift optionals in code snippets

pages/getting-started/webhooks.md
=> Update webhook authentication directions

pages/third-party-integrations/localytics.md
=> add localytics mappings

ISSUE_TEMPLATE, pages/features/facebook-ads.md, pages/features/facebook-app-invites.md, pages/methods-endpoints/data-export-api.md, pages/third-party-integrations/amplitude.md, pages/third-party-integrations/appboy.md, pages/third-party-integrations/google-analytics.md, pages/third-party-integrations/localytics.md, pages/third-party-integrations/mixpanel.md, pages/third-party-integrations/strategic-partners-guide.md, pages/third-party-integrations/tune.md
=> No more support! ;)

js/components/SearchBar.jsx
=> Use onFocus instead of onClick for search trigger

pages/features/google-search-ads.md
=> warning in pre req section

pages/getting-started/configuring-links.md
=> og + twitter tags

pages/getting-started/sdk-integration-guide.md
@aeromusek @sojanpr From support. We should push for GAID by default since it makes Branch better.
=> use gaid by default

pages/third-party-integrations/remote-deep-links.md
3P deep link creation instructions.
=> add remote DL docs

pages/getting-started/sdk-integration-guide.md
@sojanpr @aaustin could I get a thumb that I updated the right things here? I'm not sure I totally understand the technical change so I might have missed something...
=> Updates for Android SDK 2.0

pages/third-party-integrations/google-analytics.md
=> GA session management

pages/third-party-integrations/tune.md
@aeromusek at your conwenience
=> small changes to tune docs

_data/sidebar.yml, pages/third-party-integrations/other-esp.md, pages/third-party-integrations/sendgrid.md
@wlindemann please give this a glance. a few things:
- doesn't discuss how ESPs can support web-only links
- i don't know why we have both "advanced" and "support" sections, or what should go in each
- i may be missing stuff, so i'd love to have someone like @aeromusek go through and ask me questions where i haven't made it clear enough
=> information for other ESPs that want to support branch deep links

ingredients/email-paid-integration.md, pages/third-party-integrations/other-esp.md, pages/third-party-integrations/remote-deep-links.md, pages/third-party-integrations/sendgrid.md
@aeromusek merging a bunch of cleanup, we can update later. Thanks!
CC @derrickstaten
=> update email docs

pages/getting-started/configuring-links.md
=> add twitter player tag

pages/features/facebook-ads.md
=> Fewer Clicks Recorded in Branch

pages/getting-started/configuring-links.md
=> https://branch.atlassian.net/browse/INTENG-2690

_data/sidebar.yml, pages/features/chrome-extension.md, pages/getting-started/hosted-deep-link-data.md, pages/third-party-integrations/google-analytics.md, pages/third-party-integrations/other-esp.md
@aeromusek I'm actually super excited about this. Can we merge it quickly (even if it is hidden) and then edit it later? Two customers are waiting on it.
=> small fixes and hosted dl data

pages/getting-started/configuring-links.md
https://branch.atlassian.net/browse/INTENG-2690
=> updated publicly_indexable default value

pages/features/content-sharing.md
https://branch.atlassian.net/browse/INTENG-2769
=> updated the correct code for swift on content sharing

_data/platforms.yml, pages/getting-started/deep-link-routing.md, pages/getting-started/sdk-integration-guide.md, pages/getting-started/universal-app-links.md
=> iMessage integration support

pages/getting-started/webhooks.md
=> added information about device data

pages/getting-started/universal-app-links.md
@dwestgate I updated the Universal Links app support table and it ended up being a much more significant change. @djgamboa and @TheMarshal99 are waiting on this to send to a partner.
=> Updated the app support table

pages/getting-started/webhooks.md
=> update link click filter keys

pages/getting-started/link-behavior.md
=> update twitter behavior

pages/getting-started/sdk-integration-guide.md
Updated the syntax for initSession, continue userActivity, and openURL
=> Updated Code Snippets

pages/third-party-integrations/omniture.md
It ain't pretty, but it's better than an unresolved link and will funnel partners to us.
=> add omniture docs

pages/getting-started/twig-app-validator.md, pages/getting-started/universal-linking-validator.md
@dwestgate @aaustin New page for the Twig Validator (in prep for it going out this week)
=> Created Twig validator page

pages/getting-started/sdk-integration-guide.md
issue fixed: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/pull/238
=> fix: updated cordova to use npm again

pages/getting-started/universal-app-links.md
=> add gmail + inbox to list of supported UL apps

pages/getting-started/link-behavior.md
=> Updated typo.

js/components/Sidebar.jsx, pages/features/deep-linked-feeds.md
=> Let's get some stars

pages/features/google-app-indexing.md
Documentation for new **autoAppIndex()** function
cc. @aaustin
=> documentation for WebSDK app indexing function

pages/getting-started/universal-app-links.md
Add a link to the new Universal Links validator in the troubleshooting section of ULV setup.
@aaustin Can you 👍 ?
=> Add pro-tip for ULV

pages/features/journeys.md
=> fix for setBranchViewData() example

pages/third-party-integrations/mixpanel.md
=> adding additional resources for identity management in Mixpanel

pages/getting-started/branch-universal-object.md, pages/getting-started/creating-links-in-apps.md, pages/getting-started/creating-links.md, pages/getting-started/deep-link-routing.md, pages/getting-started/sdk-integration-guide.md, pages/getting-started/universal-app-links.md, pages/getting-started/user-value-attribution.md
https://branch.atlassian.net/browse/INTENG-3021
=> docs: updated cordova with working code examples

pages/features/facebook-ads.md, pages/features/facebook-app-invites.md, pages/features/instagram-ads.md
@aaustin we had a Jekyll formatting issue. Fixed here, and added a few more details. Since you're the App Links expert, could you verify this?
=> Expand App Links troubleshooting steps

pages/getting-started/configuring-links.md
=> add country-specific redirects

pages/getting-started/universal-app-links.md
=> Changed a word to avoid confusion

pages/features/journeys.md
=> adding information about open_app:true for Journeys

pages/features/spotlight-indexing.md
@ahmednawar @E-B-Smith can you please check out the code snippet if it looks ok?
=> Adding a code snippet on how to use the `indexWithCallback` method.

pages/features/journeys.md
Documentation for showing a Journey via .track('pageview') and for closing a Journey programmatically via .closeJourney().
=> Reshow journey

pages/getting-started/configuring-links.md
found this missing field in the HTTP API.. needs to be more widely known
=> docs: added $marketing_title

pages/third-party-integrations/appboy-with-sendgrid.md, pages/third-party-integrations/other-esp.md
=> purge secret

pages/getting-started/user-value-attribution.md
=> add web to user value attribution page

pages/getting-started/configuring-links.md
docs for https://github.com/BranchMetrics/branch-backend/pull/4300
=> allow partners to set custom meta tags as link data 

pages/features/apple-search-ads.md, pages/getting-started/sdk-integration-guide.md
* I updated important information for using Apple Search ads.
* I added a CocoaPod install step to make sure devs update to the latest version.
* My text editor automatically strips trailing space, so some trailing spaces has been removed.
=> Updated iOS SDK Search Ad and CocoaPod information.

_includes/footer.html
=> Updated copyright year

pages/features/search.md
@aaustin @sofmac @sojanpr for your review. Last tweak hopefully.
=> Changes to content type

pages/getting-started/link-domain-subdomain.md
Message warns users that the namespace servers are going to be unique for their custom domain.
=> Added messaging for custom domains.

pages/getting-started/configuring-links.md, pages/getting-started/matching-accuracy.md, pages/getting-started/webhooks.md, pages/third-party-integrations/tune.md
Forgot to actually push this up yesterday 😬
=> No fingerprinting

_data/sidebar.yml, index.html, js/components/Sidebar.jsx, pages/cross-channel-analytics/index.md, pages/data-exchange/index.md, pages/marketing-channels/index.md
=> add some stuff

_includes/trackers.html
@ethanneff, I've tested this and it's going out on all our other sites too, but maybe you can give a thumb here now that you're the main docs guy? 😄
=> Custom Google Analytics dimension for first touch landing page

pages/getting-started/sdk-integration-guide.md
=> Added cautionery note to set launch mode for the Activity to SingleTask

css/inner.scss
=> docs: made each page full with to respond to any screen size

pages/marketing-channels/android-instant-apps.md
This makes things a bit more readable (section links at the top of the page, etc.)
@aaustin @ethanneff
=> Use sections for Android Instant Apps

pages/getting-started/deep-link-routing.md
The guide added for new API - registerDeepLinkController: forKey: withOption:
http://127.0.0.1:4000/getting-started/deep-link-routing/advanced/ios/#register-view-controller-for-deep-link-routing
=> Support guide added for showViewController - AIS-254

pages/getting-started/sdk-integration-guide.md
fixes https://github.com/BranchMetrics/documentation/pull/535/files
=> fix open url funtion

pages/marketing-channels/journeys.md
Subheading under "Clientside Javascript Journeys controls" heading
=> Add docs for disabling Journeys animations

pages/getting-started/sdk-integration-guide.md
cc @sojanpr @EvangelosG @aaustin
=> language on default behavior

pages/marketing-channels/responsys.md
=> missing self-closing tag for responsys links

pages/getting-started/link-behavior.md
Cannot link out of Snapchat stories 🤕 https://branch.atlassian.net/browse/INTENG-3532
=> Snapchat story link warnings

pages/marketing-channels/google-app-indexing.md
https://branch.atlassian.net/browse/DOCS-109
=> Updating broken links.

pages/getting-started/link-domain-subdomain.md
=> Added a cautionary note when adding nameservers via AWS Route 53

_data/sidebar.yml, pages/marketing-channels/index.md, pages/marketing-channels/kahuna.md, pages/marketing-channels/leanplum.md, pages/marketing-channels/mailjet.md
=> new esp docs

_includes/footer.html
=> new docs floater

pages/data-exchange/localytics.md
Reverts BranchMetrics/documentation#611
=> Revert "testing redirects"

pages/getting-started/sdk-integration-guide.md
nastiness that keeps popping up
=> fix: removed old cordova docs from dev

js/all.js, package-lock.json, package.json
=> chore: update dependencies
